### ISSUE TITLE
Label Indentation

### ISSUE THREAD

**Issue by FinnWBiggs** [aulitech/auli_site#30]

**Comment by FinnWBiggs** [comment]
Please have setting fields indented under their buttons 



![Image](https://github.com/aulitech/auli_site/assets/104035223/3b930263-2d70-457c-bbb2-79de56ec5ecb)

**Comment by sperok** [comment]
![Image](https://github.com/aulitech/auli_site/assets/1141807/908f4fcc-037e-405e-a4b0-dc23a7b31196)
