### ISSUE TITLE
Bindings Panel

### ISSUE THREAD

**Issue by FinnWBiggs** [aulitech/auli_site#39]

**Comment by FinnWBiggs** [comment]
Several Items. I will split items into comments.

**Comment by FinnWBiggs** [comment]
Item 1: 

Hide None/Noop.

No gesture does nothing. User shouldn't set this. Bindings[0] is always 'noop' gesture is always 'none' -- remove it from the display.

**Comment by FinnWBiggs** [comment]
Item 2:

Dynamic nature of Gesture List.

Although current table is nice (mapping of each gesture to an atom by row), it is not complete.

The gesture list is different in clicker mode.

Each row represents a number of 'taps' that was input by the user (like single versus double-clicking a mouse)

A number of taps indexes to that entry of the bindings list. Users should be able to increase or decrease the number of bindings in clicker mode to support a range of clicks varying from 1 minimum to 6 maximum)

In short: treat gesture-atom modes as having static gesture models, but the number of taps can vary

In tap mode, change "Gesture" to "Tap Count" and add a (+) and (-) below the bottom row of the table. (Also switch to tap default as per #35 )

If you're curious about future of MyCato / specificity of design reqs, I am adding notes below

==========  Do not implement anything below this line. Notes only ============

Gesture collection (and add new gesture) is meant to enable the collection of data for custom gesture models (e.g. wearing Cato on your wrist and using arm motion to input gestures like "Roll Out/In" "Punch" "Curl" or "Clench Fist"

The consequence of this is that the gesture list is dynamic.

It will variy between users and even between a single user's registered devices to support individualized control schemas that adapt to a person's mobility.

The end use case for this system is for someone like Spero, who can still use his feet even though walking is difficult, to have a Pointer that he wears on his glasses, and a customized gesture remote that inputs click and type commands on his shoe.

**Comment by FinnWBiggs** [comment]
Update: 

Instead of a variable-length list for clicker, let's define it as a length 3 list (single, double, triple tap) bound to the defaults at first, but still editable. 

Change the gesture label to "Taps" and the "names" to "Single", "Double", "Triple"

**Comment by emilydhpark** [comment]
note to myself: change gesture --> tap count, only make single/double/triple, leave everything else the same --> (ONLY for clicker)
