### ISSUE TITLE
Move "Delete Device" up a level

### ISSUE THREAD

**Issue by FinnWBiggs** [aulitech/auli_site#41]

**Comment by FinnWBiggs** [comment]
Button should be visible even when "universal settings" is closed.

e.g. 



![Image](https://github.com/aulitech/auli_site/assets/104035223/71af3787-4d44-4ff0-a082-da479d145fd4)

**Comment by sperok** [comment]
does not right justify on wide screen

![Image](https://github.com/aulitech/auli_site/assets/1141807/615cfb3a-fa20-465e-8c7b-0dccc1ce4dec)
