### ISSUE TITLE
Include link to Video tutorial on "Bindings"

### ISSUE THREAD

**Issue by FinnWBiggs** [aulitech/auli_site#44]

**Comment by FinnWBiggs** [comment]
I will make a video explaining bindings within the next few days. I'd like for there to be a "watch tutorial" button next to the bindings panel that links to that (not yet made) video.

I'll provide a link to the video in a subsequent comment when it's done

**Comment by sperok** [comment]
![Image](https://github.com/aulitech/auli_site/assets/1141807/77f7fd14-9dd3-44f6-92d1-96816ffb4fe5)
